local beautiful = require("beautiful")
local gtk = beautiful.gtk.get_theme_variables()

local colors = {
	font_size = gtk.font_size,
	font_family = gtk.font_family,
	bg_color = gtk.bg_color,
	fg_color = gtk.fg_color,
	base_color = gtk.base_color,
	text_color = gtk.text_color,
	button_bg_color = gtk.button_bg_color,
	button_fg_color = gtk.button_fg_color,
	button_border_color = gtk.button_border_color,
	button_border_radius = gtk.button_border_radius,
	button_border_width = gtk.button_border_width,
	selected_bg_color = gtk.selected_bg_color,
	selected_fg_color = gtk.selected_fg_color,
	menubar_bg_color = gtk.menubar_bg_color,
	menubar_fg_color = gtk.menubar_fg_color,
	header_button_bg_color = gtk.header_button_bg_color,
	header_button_fg_color = gtk.header_button_fg_color,
	header_button_border_color = gtk.header_button_border_color,
	error_color = gtk.error_color,
	error_bg_color = gtk.error_bg_color,
	error_fg_color = gtk.error_fg_color,
	warning_color = gtk.warning_color,
	warning_bg_color = gtk.warning_bg_color,
	warning_fg_color = gtk.warning_fg_color,
	success_color = gtk.success_color,
	success_bg_color = gtk.success_bg_color,
	success_fg_color = gtk.success_fg_color,
	tooltip_bg_color = gtk.tooltip_bg_color,
	tooltip_fg_color = gtk.tooltip_fg_color,
	osd_bg_color = gtk.osd_bg_color,
	osd_fg_color = gtk.osd_fg_color,
	osd_border_color = gtk.osd_border_color,
	wm_bg_color = gtk.wm_bg_color,
	wm_border_focused_color = gtk.wm_border_focused_color,
	wm_border_unfocused_color = gtk.wm_border_unfocused_color,
	wm_title_focused_color = gtk.wm_title_focused_color,
	wm_title_unfocused_color = gtk.wm_title_unfocused_color,
	wm_icons_focused_color = gtk.wm_icons_focused_color,
	wm_icons_unfocused_color = gtk.wm_icons_unfocused_color,
}

return colors
