return {
    background = "#26233a",
    background2 = "#2d2b38",
    background3 = "#353340",
    foreground = "#e0def4",
    selection = "#403d52",
    border = "#ebbcba",
    black = "#16141f",
    accent = "#ebbcba",
    red = "#eb6f92",
    orange = "#ebbcba",
    green = "#ABE9B3",
    yellow = "#f6c177",
    blue = "#8bbec7",
    purple = "#bb9ede",
    aqua = "#9ccfd8",
    gray = "#e0def4",
    brightblack = "#908caa",
    brightred = "#eb6f92",
    brightorange = "#ebbcba",
    brightgreen = "#ABE9B3",
    brightyellow = "#f6c177",
    brightblue = "#8bbec7",
    brightpurple = "#c4a7e7",
    brightaqua = "#a3d6df",
    brightgray = "#6e6a86",
    wallpaper = "assets/cat.jpg",
}
